CFLAGS = -std=c99 -Wall -Wno-unused-variable -Wno-deprecated-declarations -DMAX_ITERS=100 -DNTH=8 -DOSX -DBUF_SZ=64 -DVERBOSE_MT=0 -DW1=6 -DW2=7
# If you have a GPU, add this to your CFLAGS: -DGPU

CC = gcc
ALL = testbench

all: $(ALL)


testbench: testbench.o driver.o
	$(CC) testbench.o driver.o -framework OpenCL -o testbench 


testbench.o: testbench.c
	$(CC) $(CFLAGS) -pthread -c testbench.c

driver.o: driver.c
	$(CC) $(CFLAGS) -c driver.c

clean:
	rm *.o testbench
